server:
  app_name: "PushPost Auth-Service"
  port: 8082
  address: "0.0.0.0"
database:
  host: ${AUTH_DB_HOST}
  user: ${AUTH_DB_USER}
  password: ${AUTH_DB_PASSWORD}
  db_name: ${AUTH_DB_NAME}
  port: ${AUTH_DB_PORT}
  ssl_mode: ${AUTH_DB_SSL_MODE}
  schema: "public"
jwt_secret: ${JWT_SECRET}
